### ISSUE TITLE
Code release related issues

### ISSUE THREAD

**Issue by ZhangDaXin89** [pbehjatii/FENet#1]
Hello, author, the idea of this paper is very inspiring to me, I would like to learn your code implementation, may I ask when the code can be released?

**Comment by pbehjatii** [comment]
Hello Zhang. Thank you for your interest in our paper. Next week the code will be released.

**Comment by ZhangDaXin89** [comment]
Thank you!

**Comment by pbehjatii** [comment]
The code is released.
