### ISSUE TITLE
No checkpoint directory.

### ISSUE THREAD

**Issue by sunohm** [pbehjatii/FENet#2]
Hi，pbehjatii.
Where should I download the pre trained models？

**Comment by pbehjatii** [comment]
Next week we will release the pre-trained models.

**Comment by sunohm** [comment]
Thank you. I'm looking forward to it.








smengxin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pbehjatii/FENet-PyTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月3日(星期一) 晚上9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pbehjatii/FENet-PyTorch] No checkpoint directory. (Issue #2)





 
Next week we will release the pre-trained models.

**Comment by sunohm** [comment]
Hi，pbehjatii.
Sorry to bother you again, because I still haven't found the checkpoint directory.

**Comment by pbehjatii** [comment]
Hi,
The checkpoint for scale factor x4 has been released. Please note that the code has been modified. Therefore, you need to download the new version of the code.

**Comment by sunohm** [comment]
I see an update. Thank you very much.
